os:
  - linux

sudo: true

language: java

env:
  matrix:
    - SUBPROJECT=HIRS_Utils
    - SUBPROJECT=HIRS_Provisioner
    - SUBPROJECT=HIRS_ProvisionerTPM2
    - SUBPROJECT=HIRS_Structs
    - SUBPROJECT=HIRS_AttestationCA
    - SUBPROJECT=HIRS_AttestationCAPortal
    - SUBPROJECT=TPM_Utils
    - SUBPROJECT=tpm_module

services:
  - docker

before_install:
  - docker pull hirs/hirs-ci:centos7

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

script:
  - docker run --rm hirs/hirs-ci:centos7 /bin/bash -c "git clone https://github.com/nsacyber/HIRS.git /root/HIRS; cd /root/HIRS; git checkout ${TRAVIS_BRANCH}; ./gradlew :$SUBPROJECT:build"
